// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDds9U2yqScltIPHaD3q3lAbjEXxcC7-gE',
    appId: '1:1507202135:web:046be9d61db525c9403f12',
    messagingSenderId: '1507202135',
    projectId: 'prodtrack-app',
    authDomain: 'prodtrack-app.firebaseapp.com',
    storageBucket: 'prodtrack-app.firebasestorage.app',
    measurementId: 'G-3EQC50CTGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcPPcvXyA-hVy-TfglCjHv2Xuwu7oJGi4',
    appId: '1:1507202135:android:770af3ec751ca0a4403f12',
    messagingSenderId: '1507202135',
    projectId: 'prodtrack-app',
    storageBucket: 'prodtrack-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANyzw1y6Ca2smEdpZMm35XqiV4-WonWFA',
    appId: '1:1507202135:ios:3864c47f87e181ce403f12',
    messagingSenderId: '1507202135',
    projectId: 'prodtrack-app',
    storageBucket: 'prodtrack-app.firebasestorage.app',
    iosBundleId: 'com.prodtrack.prodtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANyzw1y6Ca2smEdpZMm35XqiV4-WonWFA',
    appId: '1:1507202135:ios:3864c47f87e181ce403f12',
    messagingSenderId: '1507202135',
    projectId: 'prodtrack-app',
    storageBucket: 'prodtrack-app.firebasestorage.app',
    iosBundleId: 'com.prodtrack.prodtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDds9U2yqScltIPHaD3q3lAbjEXxcC7-gE',
    appId: '1:1507202135:web:f604d7d524c2890e403f12',
    messagingSenderId: '1507202135',
    projectId: 'prodtrack-app',
    authDomain: 'prodtrack-app.firebaseapp.com',
    storageBucket: 'prodtrack-app.firebasestorage.app',
    measurementId: 'G-ZQ7KE0EXC3',
  );
}
